services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      custom-bridge:
        ipv4_address: 172.18.0.2
    restart: always

  metasploitable:
    image: shawn102602/metasploitable
    container_name: metasploitable
    ports:
      - "8080:80"
      - "8180:8180"
    networks:
      custom-bridge:
        ipv4_address: 172.18.0.3
    restart: always
    command: /bin/bash -c "/bin/services.sh && tail -f /dev/null"

 ubuntu-ctf: # Testing Purposes
    image: ubuntu:latest
    container_name: ctf
    ports:
      - "8091:80"
    networks:
      custom-bridge:
        ipv4_address: 172.18.0.4
    restart: always
    volumes:
      - ./ctf_install.sh:/root/.ctf_install.sh
    command: /bin/bash -c "chmod +x /root/.ctf_install.sh && /root/.ctf_install.sh && tail -f /dev/null"

#  ubuntu-ctf:
#    image: shawn102602/ctf
#    container_name: ctf
#    ports:
#      - "8091:80" # Map internal port 80 to external port 8091
#    networks:
#      custom-bridge:
#        ipv4_address: 172.18.0.4
#    restart: always
#    command: /bin/bash -c "chmod +x /root/.ctf.sh && /root/.ctf.sh && tail -f /dev/null"

networks:
  custom-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
